-- [부동산 매물/중개사 테이블 생성 SQL]
-- Supabase 대시보드 -> SQL Editor -> New Query 에 붙여넣고 Run 해주세요.

-- 1. real_estate 테이블 생성
create table if not exists public.real_estate (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id), -- 작성자 ID (Supabase Auth 연동)
    company_name text not null,
    ceo_name text not null,
    registration_number text,
    business_number text,
    address text not null,
    address_detail text,
    lat float8 not null,
    lng float8 not null,
    phone_mobile text,
    phone_office text,
    description text,
    start_date date,
    end_date date,
    inquiry_url text,
    website_url text,
    youtube_url text,
    blog_url text,
    instagram_url text,
    facebook_url text,
    threads_url text,
    created_at timestamptz default now()
);

-- 2. 검색 및 지도 조회를 위한 인덱스 생성
create index if not exists real_estate_geo_idx on public.real_estate (lat, lng);
create index if not exists real_estate_date_idx on public.real_estate (start_date, end_date);

-- 3. RLS(Row Level Security) 설정 (보안 강화)
alter table public.real_estate enable row level security;

-- 기존 정책 제거 (재실행 시 에러 방지)
drop policy if exists "Public read access" on public.real_estate;
drop policy if exists "Authenticated insert access" on public.real_estate;
drop policy if exists "Owner update access" on public.real_estate;
drop policy if exists "Owner delete access" on public.real_estate;

-- 정책 1: 누구나 읽을 수 있음 (SELECT)
create policy "Public read access"
on public.real_estate
for select
using (true);

-- 정책 2: 로그인한 사용자는 추가할 수 있음 (INSERT)
create policy "Authenticated insert access"
on public.real_estate
for insert
with check (auth.role() = 'authenticated');

-- 정책 3: 본인이 작성한 글만 수정 가능 (UPDATE)
create policy "Owner update access"
on public.real_estate
for update
using (auth.uid() = user_id);

-- 정책 4: 본인이 작성한 글만 삭제 가능 (DELETE)
create policy "Owner delete access"
on public.real_estate
for delete
using (auth.uid() = user_id);
